### ISSUE TITLE
Possibility to use auhtorization header

### ISSUE THREAD

**Issue by sassanh** [core-api/javascript-client#32]
Is it possible to have an equivalent of `coreapi credentials add` in js version?

**Comment by sassanh** [comment]
Now I saw it's first issue here and that this repo is created ~4 months ago.
Is a production ready version scheduled?
I'm willing to contribute to this project if any help is required.

**Comment by tomchristie** [comment]
> Is it possible to have an equivalent of coreapi credentials add in js version?

Yup, incoming.

> Is a production ready version scheduled?

Yes, a 1.0 release will be available fairly shortly.
