### ISSUE TITLE
Promisse fails when response has no content type.

### ISSUE THREAD

**Issue by nurv** [core-api/javascript-client#39]
When calling DELETE django rest framework using core api, it throws an exception.

The cause for this is that DRF removed the header for content type on 204 responses. In [this line](https://github.com/core-api/javascript-client/blob/master/lib/transports/http.js#L12) the result from calling `get` over the Headers object when that header doesn't exist is `null`. However in [this line](https://github.com/core-api/javascript-client/blob/master/lib/utils.js#L17)  the check is made for `undefined` not `null`. This check fails, causing it to fail in [this line](https://github.com/core-api/javascript-client/blob/master/lib/utils.js#L21) by dereferencing null.

**Comment by audiolion** [comment]
sounds like you did a lot of great work tracking down the source of the error, I would just formalize this all into a PR and a maintainer will review with time. I am pretty sure the author intends to maintain, but he also has a lot of other projects he oversees

**Comment by tomchristie** [comment]
Resolved via #37.
New release incoming shortly.
